version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin
    volumes:
      - ~/jenkins_compose_data/jenkins_configuration:/var/jenkins_home
      - ~/jenkins_compose_data/docker.sock:/var/run/docker.sock
#      - ./pipeline_project:/var/aqa_api_tests
    dns:
      - 8.8.8.8
      - 8.8.4.4